version: '3.8'

services:
    estate-streamlit:
        build: 
            context: .  # the path to the directory containing the Dockerfile.
            # dockerfile: Dockerfile
            # platform: linux/amd64  # Specify the platform architecture here
        # image: estate_lookout-estate-streamlit
        ports: 
            - 8501:8501

